name: Send Email

inputs:
  to_email:
    description: 'Recipient email address'
    required: true
  from_email:
    description: 'Sender email address'
    required: true
  smtp_server:
    description: 'SMTP server address'
    required: true
  smtp_port:
    description: 'SMTP server port'
    required: true
  smtp_username:
    description: 'SMTP username'
    required: true
  smtp_password:
    description: 'SMTP password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Send email
      shell: bash
      run: python ${{ github.action_path }}/send_mail.py
      env:
        TO_EMAIL: ${{ inputs.to_email }}
        FROM_EMAIL: ${{ inputs.from_email }}
        SMTP_SERVER: ${{ inputs.smtp_server }}
        SMTP_PORT: ${{ inputs.smtp_port }}
        SMTP_USERNAME: ${{ inputs.smtp_username }}
        SMTP_PASSWORD: ${{ inputs.smtp_password }}